title: Diego's Corner on the Net

author:
  name: Diego Lobba
  email: diego.lobba [at] gmail.com

encoding: UTF-8
theme: minima

description: >
  My tiny space on the internet.
  Opinions are my own.

show_excerpts: false

github_username: dlobba
linkedin_username: diego-lobba

header_pages:
  - index.md
  - projects.md
  - contacts.md
  - about.md

titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
